# Load modules
import glob
import os
import subprocess
import pdb
import shutil

# Get the date
from datetime import datetime
i = datetime.now()
TIME = i.strftime('%Y-%m-%d')

# Specify config file
configfile: "workflow/config.yml"

# Parse config.yml file
SCRATCH = config['dir']['scratch']
OUT = config['dir']['out']
QUERY = config['query']
RF_GEN = config['rfmix']['generations']
RF_REANALYZE = config['rfmix']['reanalyze_reference']
RF_REFPOPS = config['rfmix']['ref_pops']
RF_POPNAME = config['rfmix']['pop_names']
CHROMS = config['chroms']
PCNUM = config['admixMapping_PCnum']
REFFILE = config['reference']['vcf']
POPFILE = config['reference']['subpops']
MAPFILE = config['reference']['genmap']

if config['reference']['phased_bcf'] == 'none':
    REFBCF=f"{os.getcwd()}/bcfs/{os.path.basename(REFFILE).strip('.gz').strip('.vcf').strip('.bcf')}.subset.bcf"
elif os.path.exists(config['reference']['phased_bcf']):
    REFBCF=config['reference']['phased_bcf']
else:
    print("Did not find phased BCF file at " + config['reference']['phased_bcf'])

if config['singularity']['use_singularity'] == 'true' and config['singularity']['image'] != "none":
    bind_paths = ",".join(set([os.path.dirname(x) for x in [QUERY, REFFILE, POPFILE, MAPFILE, REFBCF]]))
    CMD_PREFIX = f"set +u; module load singularity; singularity exec --bind {bind_paths},{os.getcwd()} {config['singularity']['image']}"
    #He has to specify version of singularity...
    CODE = config['singularity']['code']
else:
    CMD_PREFIX = config['cmd_prefix']
    CODE = config['dir']['code']

BASE = config['outname']  # Base prefix used for naming files is set as basename of
INPUT = f"input/{BASE}"

# If set to true, the reference populations will be reanalyzed.  Useful for when reference populations are themselves admixed.
if RF_REANALYZE == 'true':
    RF_REANALYZE = '--reanalyze-reference -e 6'
else:
    RF_REANALYZE = ''

# Set default internal variables
PHASE_MAP = "accessory/Shapeit4_genetic_map"
NEW_POPFILE = "accessory/Population_Map_File.txt"

INDS = []
with open(QUERY + ".fam", 'r') as pop_file:
    for line in pop_file:
        ind = line.strip().split()[0]
        INDS.append(ind)

if CHROMS == 'all':
    CHROMS = [str(x) for x in range(1, 23)]

# Make subdirectories
dirs = ["input", "vcfs", "bcfs", "rfmix", "accessory", "beds", "karyograms", "plink", "OandE"]
for directory in dirs:
    if not os.path.exists(directory): os.mkdir(directory)

localrules: all, phase_map, pop_map

RFMIX_OUT = expand(f"rfmix/{BASE}.chr{{chrom}}.rfmix.Q", chrom=CHROMS)

rule all:
    input:
        f"{INPUT}.bed",
        f"bcfs/{os.path.basename(REFBCF)}",
        expand(f"bcfs/{BASE}.chr{{chrom}}.phz.bcf", chrom=CHROMS),
        expand(f"rfmix/{BASE}.chr{{chrom}}.rfmix.Q", chrom=CHROMS)
#         expand(f"beds/{{ind}}_A.bed", ind=INDS),
#         expand(f"karyograms/{{ind}}_karyo.png", ind=INDS),

rule clean:
    shell:
        "rm vcfs/*; rm bcfs/*; rm rfmix/*; rm beds/*; rm karyograms/*"

rule QCcombine_query:
    input: f"{QUERY}.bed"
    output: f"{INPUT}.bed"
    params:
        tvm1 = config['QC']['vm1'], tgm = config['QC']['gm'], tvm2 = config['QC']['vm2'],
        hwe = config['QC']['hwe'], maf = config['QC']['maf'], mbs = config['QC']['mbs']
    run:
        if config['perform_QC'] == 'true':
            shell(f"{CMD_PREFIX} python {CODE}/QC.py -i {{input}} -d input/ -o {BASE} -t {{threads}} -p plink -tvm1 {{params.tvm1}} -tgm {{params.tgm}} -tvm2 {{params.tvm2}} -hwe {{params.hwe}} -mbs {{params.mbs}} -maf {{params.maf}}")
        else:
            shell(f"{CMD_PREFIX} plink --bfile {QUERY} --make-bed --out {INPUT}")

rule parse_plink:
    input: f"{INPUT}.bed"
    output: f"vcfs/{BASE}.chr{{chrom}}.vcf"
    shell: f"{CMD_PREFIX} plink --bfile {INPUT} --chr {{wildcards.chrom}} --keep-allele-order --out vcfs/{BASE}.chr{{wildcards.chrom}} --recode vcf-iid"

rule compress_and_index:
    input: f"vcfs/{BASE}.chr{{chrom}}.vcf"
    output: f"vcfs/{BASE}.chr{{chrom}}.vcf.gz"
    shell: f"{CMD_PREFIX} bgzip {{input}}; {CMD_PREFIX} tabix -p vcf {{output}}"

rule phase_map:
    input: MAPFILE
    output: "accessory/Shapeit4_genetic_map{chrom}"
    shell: "{CMD_PREFIX} python3.6 {CODE}/phase_map.py -i {input}"

rule pop_map:
    input: POPFILE
    output: "accessory/Population_Map_File.txt"
    shell: f"{CMD_PREFIX} python3.6 {CODE}/pop_map.py -i {{input}} -p {RF_REFPOPS} -n {RF_POPNAME} -o {NEW_POPFILE}"

rule prep_RefVCF:
    input: REFFILE, "accessory/Population_Map_File.txt"
    output: f"bcfs/{os.path.basename(REFBCF)}"
    run:
        if config['reference']['phased_bcf'] == 'none' or config['singularity']['use_singularity'] == 'true':
            with open('prep_RefVCF.sh', 'w') as temp_sh:
                temp_sh.write(f"awk \'{{print $1}}\' {input[1]} | bcftools view -S - {input[0]} -Ob -o {output} --force-samples --threads {config['bcftools']['threads']}; bcftools index {output} --threads {config['bcftools']['threads']}\n")
            shell("{CMD_PREFIX} sh prep_RefVCF.sh")
        else:
            shutil.copy(REFBCF, f"bcfs/{os.path.basename(REFBCF)}")

rule phase:
    input:
        f"vcfs/{BASE}.chr{{chrom}}.vcf.gz",
        "accessory/Shapeit4_genetic_map{chrom}",
        f"bcfs/{os.path.basename(REFBCF)}"
    output: f"bcfs/{BASE}.chr{{chrom}}.phz.bcf"
    threads: int(config['phase']['threads'])
    shell:
        f"{CMD_PREFIX} shapeit4 -I {{input[0]}} -M {PHASE_MAP}{{wildcards.chrom}} -O {{output}} --region {{wildcards.chrom}} --pbwt-depth {config['phase']['pbwt_depth']} -T {{threads}} --reference {{input[2]}} --log bcfs/{BASE}.chr{{wildcards.chrom}}.phz.bcf.log && {CMD_PREFIX} bcftools index {{output}} --threads {{threads}}"

rule infer_ancestry:
    input: f"bcfs/{BASE}.chr{{chrom}}.phz.bcf", "accessory/Population_Map_File.txt"
    output: f"rfmix/{BASE}.chr{{chrom}}.rfmix.Q"
    threads: int(config['rfmix']['threads'])
    shell:
        f"{CMD_PREFIX} rfmix -f {{input[0]}} -r {REFBCF} -m {{input[1]}} -g {MAPFILE} -s {config['rfmix']['window_size']} -o rfmix/{BASE}.chr{{wildcards.chrom}} --chromosome={{wildcards.chrom}} --n-threads={{threads}} -G {RF_GEN} {RF_REANALYZE}"

rule make_hap_beds:
    input: RFMIX_OUT
    output: "beds/{ind}_A.bed"
    run:
        with open(f"{wildcards.ind}_A.sh", 'w') as temp_sh:
            temp_sh.write(f"source activate py27; python {CODE}/msp2bed.py --rfmix rfmix/{BASE} --ind {wildcards.ind} --out beds/{wildcards.ind}\n")
        shell(f"{CMD_PREFIX} {{wildcards.ind}}_A.sh; rm {{wildcards.ind}}_A.sh")

rule plot_karyograms:
    input: "beds/{ind}_A.bed"
    output: "karyograms/{ind}_karyo.png"
    shell:
        f"{CMD_PREFIX} source activate py27; python {CODE}/plot_karyogram.py --bed_a beds/{{wildcards.ind}}_A.bed --bed_b beds/{{wildcards.ind}}_B.bed --ind {{wildcards.ind}} --centromeres accessory/centromeres_hg19.bed --pop_order beds/pop_order.txt --out karyograms/{{wildcards.ind}}_karyo.png"

rule make_hap_beds_wQual:
    input: RFMIX_OUT
    output: "beds/{ind}_A_Qual.bed"
    run:
        with open(f"{wildcards.ind}_A.sh", 'w') as temp_sh:
            temp_sh.write(f"source activate py27; python {CODE}/msp2bed.py --rfmix rfmix/{BASE} --ind {wildcards.ind} --out beds/{wildcards.ind} --Qual\n")
        shell(f"{CMD_PREFIX} {{wildcards.ind}}_A.sh; rm {{wildcards.ind}}_A.sh")
